alias undopush="push -f origin HEAD^:master"
alias undocommit="git reset --soft HEAD^"
alias am='cd ~/workspace/reflex-am'
alias amweb='cd ~/workspace/reflex-am-web'
alias l.='ls -dl .*'
alias breset='. ~/.bash_profile'
#alias mdj='mvnDebug jetty:run'
alias gpod='git push origin develop'
alias gffc='git flow feature checkout'
